import { chromium } from 'playwright'
const BASE = 'http://localhost:3000'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1400, height: 1050 } })
const page = await ctx.newPage()
page.on('response', (r) => { if (r.status() >= 500) console.log('HTTP', r.status(), r.url().slice(0, 80)) })
await page.goto(`${BASE}/login`)
await page.fill('input[type=email]', 'father@test.in')
await page.fill('input[type=password]', 'pumpbook123')
await page.click('button[type=submit]')
await page.waitForURL((u) => !u.pathname.includes('/login'), { timeout: 60000 })
await page.goto(`${BASE}/settings`, { waitUntil: 'load' })
await page.waitForTimeout(1000)

const body = () => page.locator('main').innerText()
console.log('--- 1. as it opens ---')
console.log((await body()).slice(0, 260))

const edit = page.getByRole('button', { name: 'Pump details' })
console.log('\nedit buttons:', await edit.count())
await edit.first().click()
await page.waitForTimeout(600)
console.log('\n--- 2. after pressing edit ---')
console.log((await body()).slice(0, 300))

const form = page.locator('form').filter({ has: page.locator('input[name=invoice_prefix]') })
const stamp = String(Date.now()).slice(-5)
await form.locator('input[name=name]').fill(`Rathod Petroleum ${stamp}`)
await form.locator('button[type=submit]').first().click()
await page.waitForTimeout(3500)
console.log('\n--- 3. after saving ---')
console.log((await body()).slice(0, 260))
console.log('\nback to a read-only view?', !(await page.locator('input[name=invoice_prefix]').count()))
console.log('shows the new name?', (await body()).includes(stamp))
await browser.close()
